name: Demo Python Script Workflow

on:
  workflow_dispatch:   
  push:
    branches:
      - master       
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Move source code for runner environment
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Run script
        id: run_script
        env:
          MY_VARIABLE: ${{ vars.MY_VARIABLE }}
          MY_STRING: ${{ secrets.MY_STRING }}
        run: |
          python script.py "${MY_VARIABLE}" "${MY_STRING}"
          echo "result=$(cat output.txt)" >> $GITHUB_OUTPUT

      - name: Write to summary
        run: |
          echo "### Script Result" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.run_script.outputs.result }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output.txt
